const SKILLS_RAW = [
  "Communication",
  "Problem Solving",
  "Teamwork",
  "Leadership",
  "Time Management",
  "Adaptability",
  "MS Office",

  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "React",
  "React Native",
  "Next.js",
  "Node.js",
  "Express.js",
  "GraphQL",
  "REST APIs",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "AWS",
  "Google Cloud",
  "Azure",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Git",
  "Linux",
  "Bash/Shell",
  "Testing (Jest/Cypress)",
  "Microservices",
  "Terraform",
  "OAuth/SSO",
  "Cybersecurity",

  "Figma",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "After Effects",
  "Premiere Pro",
  "UI/UX Design",
  "Wireframing",
  "Prototyping",
  "Design Systems",
  "Interaction Design",
  "Visual Design",
  "Typography",
  "Accessibility (WCAG)",
  "Usability Testing",
  "User Research",
  "Branding",
  "Iconography",
  "Motion Graphics",
  "3D Design (Blender/C4D)",
  "Responsive Web Design",

  "Patient Care",
  "Clinical Documentation",
  "EMR/EHR (Epic/Cerner)",
  "Medical Terminology",
  "Vitals Monitoring",
  "Phlebotomy",
  "Medication Administration",
  "Wound Care",
  "Triage",
  "HIPAA Compliance",
  "Infection Control",
  "Sterilization",
  "First Aid",
  "BLS/CPR",
  "Medical Billing & Coding (ICD-10/CPT)",
  "Insurance Verification",
  "Telehealth",
  "Patient Education",
  "Appointment Scheduling",

  "Curriculum Development",
  "Instructional Design",
  "Lesson Planning",
  "Classroom Management",
  "Differentiated Instruction",
  "Assessment Design",
  "Learning Objectives",
  "LMS (Canvas/Moodle)",
  "eLearning Tools",
  "Storyline/Captivate",
  "Google Classroom",
  "Public Speaking",
  "Training Facilitation",
  "Coaching & Mentoring",
  "Educational Technology",
  "Special Education",
  "Parent Communication",
  "Student Data Tracking",

  "Bookkeeping",
  "Accounts Payable",
  "Accounts Receivable",
  "Bank Reconciliation",
  "Financial Analysis",
  "Financial Modeling",
  "Budgeting & Forecasting",
  "Variance Analysis",
  "Auditing",
  "Tax Preparation",
  "GAAP/IFRS",
  "Cost Accounting",
  "Payroll",
  "Risk Management",
  "Excel (Pivot/Lookup)",
  "Power BI/Tableau",
  "QuickBooks",
  "SAP/Oracle Financials",

  "AutoCAD",
  "SolidWorks",
  "CATIA/Creo",
  "FEA (ANSYS)",
  "CFD",
  "MATLAB",
  "PCB Design (Altium)",
  "Circuit Design",
  "Embedded Systems",
  "PLC Programming",
  "Root Cause Analysis",
  "DFMEA/PFMEA",
  "Lean/Six Sigma",
  "Tolerance Analysis",
  "CNC/CAM",
  "Project Management",
  "MS Project",
  "Standards (ASME/ISO)",

  "Sales Strategy",
  "Prospecting",
  "Negotiation",
  "Cold Outreach",
  "Pipeline Management",
  "Account Management",
  "CRM (Salesforce/HubSpot)",
  "Presentation/Demo",
  "Proposal Writing",
  "SEO",
  "Content Marketing",
  "Copywriting",
  "Email Marketing",
  "Social Media Ads",
  "Google Ads",
  "Meta Ads",
  "GA4/Analytics",
  "A/B Testing",
  "CRO (Conversion Optimization)",
  "Influencer Marketing",
  "Market Research",
  "Brand Strategy",

  "Customer Support",
  "Live Chat",
  "Email Support",
  "Phone Handling",
  "Ticketing Systems",
  "Zendesk/Freshdesk",
  "Escalation Management",
  "SLA Management",
  "Knowledge Base",
  "Order Management",
  "Returns/Refunds",
  "De-escalation",
  "Active Listening",
  "Troubleshooting",
  "NPS/CSAT",
  "Multichannel Support",
  "CRM Tools",

  "Inventory Management",
  "Warehouse Operations",
  "Forklift Operation",
  "Pick & Pack",
  "Shipping/Receiving",
  "Quality Control",
  "Lean Manufacturing",
  "5S/Kaizen",
  "Six Sigma",
  "SOP Documentation",
  "ERP/MRP (SAP)",
  "Production Planning",
  "Supply Chain",
  "Demand Planning",
  "Procurement",
  "Vendor Management",
  "Route Planning",
  "Fleet Management",
  "OSHA Compliance",

  "Recruiting",
  "Talent Sourcing",
  "Interviewing",
  "Onboarding",
  "Performance Management",
  "Employee Relations",
  "Compensation & Benefits",
  "Payroll Processing",
  "Labor Law Compliance",
  "HRIS (Workday/BambooHR)",
  "ATS (Greenhouse/Lever)",
  "HR Analytics",
  "Training & Development",
  "Policy Writing",
  "Succession Planning",
  "Employer Branding",

  "Legal Writing",
  "Contract Review",
  "Case Research",
  "Discovery",
  "Document Drafting",
  "Litigation Support",
  "Case Management",
  "Compliance",
  "Corporate Governance",
  "E-Discovery",
  "Due Diligence",
  "IP Basics",
  "Westlaw/LexisNexis",
  "Client Communication",
  "Regulatory Filings",

  "Calendar Management",
  "Scheduling",
  "Email Management",
  "Data Entry",
  "Document Management",
  "Google Workspace",
  "Meeting Minutes",
  "Travel Arrangements",
  "Reception",
  "Recordkeeping",
  "Office Management",
  "Procurement",
  "Customer Correspondence",
  "Presentation Prep",
  "File Organization",

  "Front Desk Operations",
  "Guest Services",
  "Reservations",
  "Concierge",
  "Event Planning",
  "Banquet/Catering",
  "Food & Beverage Service",
  "POS Systems",
  "Housekeeping Supervision",
  "Room Operations (OPERA)",
  "Revenue Management",
  "Yield Management",
  "OTA Management (Booking/Expedia)",
  "Tour Guiding",
  "Food Safety (ServSafe)",

  "Blueprint Reading",
  "BIM (Revit)",
  "AutoCAD (Construction)",
  "Estimating",
  "Quantity Surveying",
  "Site Supervision",
  "Safety Protocols (OSHA)",
  "Tool Safety",
  "Carpentry",
  "Masonry",
  "Concrete",
  "HVAC",
  "Electrical Work",
  "Plumbing",
  "Roofing",
  "Surveying",
  "Welding",
  "Primavera P6 Scheduling",

  "Content Strategy",
  "Copy Editing (AP Style)",
  "Journalism",
  "Scriptwriting",
  "Video Production",
  "Video Editing",
  "Podcast Production",
  "Audio Editing",
  "Photography",
  "Public Relations",
  "Press Releases",
  "Crisis Communications",
  "Social Media Management",
  "Community Management",
  "Social Analytics",
  "Media Buying",
  "CMS (WordPress)",

  "Experimental Design",
  "Hypothesis Testing",
  "Data Collection",
  "Lab Techniques",
  "Microscopy",
  "Spectroscopy",
  "Cell Culture",
  "Field Work",
  "Scientific Writing",
  "Literature Review",
  "Statistical Analysis",
  "R/SPSS",
  "Python (Pandas)",
  "Data Visualization",
  "GIS",
  "Grant Writing",
  "Ethics/IRB",
  "Research Design",

  "Critical Thinking",
  "Organization",
  "Presentation",
  "Customer Focus",
  "Basic Computer Literacy",
];

module.exports = { SKILLS_RAW };
