export const INDUSTRIES = [
  "Information Technology",
  "Design & Creative",
  "Healthcare",
  "Education & Training",
  "Finance & Accounting",
  "Engineering",
  "Sales & Marketing",
  "Customer Service",
  "Manufacturing & Logistics",
  "Human Resources",
  "Legal",
  "Administrative & Office",
  "Hospitality & Tourism",
  "Construction & Trades",
  "Media & Communication",
  "Science & Research",
  "Other",
];
