// constants/jobTitles.js
export const JOB_TITLES = [
  // Technology
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "React Developer",
  "Node.js Developer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Cybersecurity Specialist",
  "Systems Administrator",
  "QA Engineer",
  "Automation Engineer",
  "Game Developer",

  // Product & Design
  "Product Manager",
  "Project Manager",
  "Scrum Master",
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Visual Designer",
  "Motion Designer",
  "3D Artist",
  "Creative Director",

  // Business & Marketing
  "Business Analyst",
  "Operations Manager",
  "Sales Representative",
  "Sales Manager",
  "Account Executive",
  "Account Manager",
  "Customer Success Manager",
  "Marketing Specialist",
  "Marketing Manager",
  "SEO Specialist",
  "Content Strategist",
  "Copywriter",
  "Social Media Manager",
  "Brand Manager",

  // Finance & HR
  "Financial Analyst",
  "Accountant",
  "Auditor",
  "Bookkeeper",
  "Payroll Specialist",
  "HR Specialist",
  "HR Manager",
  "Recruiter",
  "Talent Acquisition Specialist",
  "Compensation & Benefits Specialist",

  // Healthcare
  "Registered Nurse",
  "Medical Assistant",
  "Physician",
  "Surgeon",
  "Pharmacist",
  "Physical Therapist",
  "Occupational Therapist",
  "Radiologic Technologist",
  "Lab Technician",
  "Healthcare Administrator",

  // Education
  "Teacher",
  "Professor",
  "Teaching Assistant",
  "Curriculum Developer",
  "Instructional Designer",
  "Educational Consultant",
  "School Administrator",
  "Tutor",
  "Trainer",

  // Logistics & Trades
  "Logistics Coordinator",
  "Supply Chain Manager",
  "Procurement Specialist",
  "Warehouse Associate",
  "Forklift Operator",
  "Construction Worker",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Mechanical Engineer",
  "Civil Engineer",

  // Media & Communication
  "Journalist",
  "Editor",
  "Content Writer",
  "Video Editor",
  "Photographer",
  "PR Specialist",
  "Community Manager",
  "Communications Manager",

  // Administrative
  "Executive Assistant",
  "Administrative Assistant",
  "Office Manager",
  "Receptionist",
  "Data Entry Clerk",
  "Virtual Assistant",
];
