export const JOB_TITLES_BY_INDUSTRY = {
  "Information Technology": [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer",
    "DevOps Engineer",
    "Data Scientist",
    "Data Analyst",
    "Machine Learning Engineer",
    "Cloud Engineer",
    "Cybersecurity Specialist",
    "QA Engineer",
    "UI/UX Designer",
    "Product Manager",
    "IT Support Specialist",
  ],

  "Design & Creative": [
    "Graphic Designer",
    "UI/UX Designer",
    "Product Designer",
    "Motion Designer",
    "Art Director",
    "Creative Director",
    "Illustrator",
    "Video Editor",
    "3D Artist",
    "Brand Designer",
    "Visual Designer",
  ],

  Healthcare: [
    "Registered Nurse",
    "Physician",
    "Medical Assistant",
    "Pharmacist",
    "Physical Therapist",
    "Occupational Therapist",
    "Radiologic Technologist",
    "Laboratory Technician",
    "Clinical Research Coordinator",
    "Healthcare Administrator",
  ],

  "Education & Training": [
    "Teacher",
    "Professor",
    "Instructional Designer",
    "Curriculum Developer",
    "Training Specialist",
    "Corporate Trainer",
    "Educational Consultant",
    "School Administrator",
  ],

  "Finance & Accounting": [
    "Accountant",
    "Auditor",
    "Financial Analyst",
    "Investment Banker",
    "Bookkeeper",
    "Payroll Specialist",
    "Risk Analyst",
    "Controller",
    "Tax Specialist",
    "Treasury Analyst",
  ],

  Engineering: [
    "Mechanical Engineer",
    "Electrical Engineer",
    "Civil Engineer",
    "Structural Engineer",
    "Industrial Engineer",
    "Manufacturing Engineer",
    "Chemical Engineer",
    "Embedded Systems Engineer",
    "Project Engineer",
  ],

  "Sales & Marketing": [
    "Sales Representative",
    "Account Executive",
    "Business Development Manager",
    "Marketing Specialist",
    "Digital Marketing Manager",
    "SEO Specialist",
    "Content Marketer",
    "Social Media Manager",
    "Brand Manager",
    "Growth Marketer",
  ],

  "Customer Service": [
    "Customer Service Representative",
    "Call Center Agent",
    "Technical Support Specialist",
    "Client Success Manager",
    "Help Desk Analyst",
    "Support Engineer",
    "Service Manager",
  ],

  "Manufacturing & Logistics": [
    "Production Worker",
    "Machine Operator",
    "Quality Assurance Inspector",
    "Warehouse Associate",
    "Logistics Coordinator",
    "Supply Chain Analyst",
    "Operations Manager",
    "Procurement Specialist",
    "Fleet Manager",
  ],

  "Human Resources": [
    "HR Specialist",
    "Recruiter",
    "Talent Acquisition Manager",
    "HR Generalist",
    "HR Business Partner",
    "Compensation Analyst",
    "Training & Development Specialist",
    "Employee Relations Manager",
  ],

  Legal: [
    "Lawyer",
    "Paralegal",
    "Legal Assistant",
    "Corporate Counsel",
    "Compliance Officer",
    "Contract Manager",
    "Legal Researcher",
  ],

  "Administrative & Office": [
    "Administrative Assistant",
    "Executive Assistant",
    "Office Manager",
    "Receptionist",
    "Data Entry Clerk",
    "Operations Coordinator",
    "Secretary",
  ],

  "Hospitality & Tourism": [
    "Hotel Manager",
    "Front Desk Agent",
    "Concierge",
    "Event Coordinator",
    "Food & Beverage Manager",
    "Chef",
    "Tour Guide",
    "Housekeeping Supervisor",
  ],

  "Construction & Trades": [
    "Construction Worker",
    "Site Supervisor",
    "Electrician",
    "Plumber",
    "Carpenter",
    "Mason",
    "HVAC Technician",
    "Welder",
    "Surveyor",
  ],

  "Media & Communication": [
    "Journalist",
    "Content Writer",
    "Copywriter",
    "Editor",
    "Public Relations Specialist",
    "Social Media Manager",
    "Broadcast Producer",
    "Podcaster",
    "Videographer",
  ],

  "Science & Research": [
    "Research Scientist",
    "Lab Technician",
    "Research Assistant",
    "Biostatistician",
    "Clinical Research Associate",
    "Environmental Scientist",
    "Data Scientist",
    "Postdoctoral Researcher",
  ],
};
