export const SKILLS_BY_INDUSTRY = {
  "Information Technology": [
    "JavaScript",
    "Python",
    "React",
    "Node.js",
    "SQL",
    "AWS",
    "Firebase",
    "Git",
    "DevOps",
    "Cybersecurity",
  ],
  "Design & Creative": [
    "Figma",
    "Photoshop",
    "Illustrator",
    "UI/UX Design",
    "Adobe XD",
    "Motion Graphics",
    "Branding",
    "3D Design",
  ],
  Healthcare: [
    "Patient Care",
    "EMR Systems",
    "Medical Terminology",
    "First Aid",
    "Clinical Procedures",
    "Medical Billing",
  ],
  "Education & Training": [
    "Curriculum Development",
    "Lesson Planning",
    "Public Speaking",
    "Classroom Management",
    "eLearning Tools",
    "Assessment Design",
  ],
  "Finance & Accounting": [
    "Bookkeeping",
    "Tax Preparation",
    "Excel",
    "Financial Analysis",
    "Auditing",
    "Budgeting",
  ],
  Engineering: [
    "AutoCAD",
    "MATLAB",
    "SolidWorks",
    "Project Management",
    "Circuit Design",
    "Thermodynamics",
    "Problem Solving",
  ],
  "Sales & Marketing": [
    "SEO",
    "Copywriting",
    "Email Marketing",
    "Sales Strategy",
    "Lead Generation",
    "Social Media Ads",
  ],
  "Customer Service": [
    "Customer Support",
    "CRM Tools",
    "Conflict Resolution",
    "Live Chat",
    "Phone Handling",
    "Ticketing Systems",
  ],
  "Manufacturing & Logistics": [
    "Inventory Management",
    "Forklift Operation",
    "Quality Control",
    "Shipping",
    "Warehouse Operations",
    "Logistics Planning",
  ],
  "Human Resources": [
    "Recruiting",
    "Onboarding",
    "HRIS Systems",
    "Payroll Processing",
    "Conflict Mediation",
    "Compliance",
  ],
  Legal: [
    "Legal Writing",
    "Case Research",
    "Document Drafting",
    "Litigation Support",
    "Client Communication",
  ],
  "Administrative & Office": [
    "Data Entry",
    "MS Office",
    "Scheduling",
    "Email Management",
    "Clerical Support",
    "File Organization",
  ],
  "Hospitality & Tourism": [
    "Hotel Management",
    "Guest Services",
    "Reservations",
    "Event Planning",
    "Tour Guiding",
    "Food & Beverage Service",
  ],
  "Construction & Trades": [
    "Blueprint Reading",
    "Carpentry",
    "Plumbing",
    "Electrical Work",
    "Safety Protocols",
    "Site Supervision",
  ],
  "Media & Communication": [
    "Video Editing",
    "Photography",
    "Public Relations",
    "Scriptwriting",
    "Social Media Management",
    "Broadcasting",
  ],
  "Science & Research": [
    "Data Collection",
    "Lab Techniques",
    "Statistical Analysis",
    "Hypothesis Testing",
    "Scientific Writing",
    "Research Design",
  ],
  Other: ["General Skills", "Multitasking", "Adaptability", "Time Management"],
};
